/**
 * @saulene/plugin — statusLine enable helpers (pure core for enable-statusline bin)
 *
 * Claude Code plugins CANNOT declare a `statusLine` — it must live in the user's
 * `~/.claude/settings.json`. Enabling the ul statusline therefore means MERGING a
 * `statusLine` block into that file without clobbering the user's real config.
 *
 * Everything here is pure (no IO): the merge helper and the launcher-script text. The
 * bin owns the only IO (read/write settings.json + write the launcher). Keeping the
 * merge pure makes the hard requirement — idempotent + non-destructive — testable.
 *
 * PATH STABILITY: the plugin installs to a VERSIONED cache path
 * (`.../saulene/saulene/<version>/...`), so a bare absolute path in settings.json would
 * break on every version bump. Instead we write a tiny stable launcher to a fixed path
 * (`<sauleneRoot>/statusline-launch.sh`) that resolves the NEWEST installed
 * statusline.js at run time and execs it. settings.json points at that launcher, so it
 * survives version bumps without ever being rewritten. This avoids depending on
 * `${CLAUDE_PLUGIN_ROOT}` being set for USER-settings statusLine commands (it isn't
 * reliably).
 */

/** The statusLine block Claude Code understands. */
export interface StatusLineConfig {
  type: "command";
  command: string;
  refreshInterval?: number;
  padding?: number;
}

/**
 * Merge a statusLine block into existing settings, preserving ALL other keys.
 * Idempotent: same (existing, command, refreshInterval) → identical result, no dup.
 *
 * @param existing        Parsed settings.json (or {} if the file was absent).
 * @param command         The resolved statusLine command string.
 * @param refreshInterval Optional re-run timer in seconds (omit for event-driven only).
 */
export function mergeStatusLineSettings(
  existing: Record<string, unknown>,
  command: string,
  refreshInterval?: number,
): Record<string, unknown> {
  const statusLine: StatusLineConfig = { type: "command", command };
  if (refreshInterval !== undefined) statusLine.refreshInterval = refreshInterval;
  return { ...existing, statusLine };
}

/**
 * Build the version-stable launcher shell script.
 *
 * At run time it globs every installed plugin version under `cacheBase`, picks the
 * newest by version sort, and execs `node` on its `statusline.js` (stdin passes through
 * via exec). If the glob finds nothing (layout changed, base missing) it falls back to
 * `fallbackTarget` — the absolute statusline.js path captured when the launcher was
 * written — so it keeps working until the next enable run regenerates it.
 *
 * @param cacheBase      Dir holding the per-version install dirs (e.g. `.../saulene/saulene`).
 * @param fallbackTarget Absolute path to the statusline.js known good at write time.
 */
export function buildLauncherScript(cacheBase: string, fallbackTarget: string): string {
  return [
    "#!/bin/sh",
    "# Saulene statusline launcher — AUTO-GENERATED by enable-statusline. Do not edit.",
    "# Resolves the newest installed statusline.js so it survives plugin version bumps.",
    `BASE=${shq(cacheBase)}`,
    `FALLBACK=${shq(fallbackTarget)}`,
    'TARGET=""',
    'if [ -d "$BASE" ]; then',
    '  for d in $(ls -d "$BASE"/*/ 2>/dev/null | sort -V); do',
    '    cand="${d}packages/plugin/dist/bin/statusline.js"',
    '    [ -f "$cand" ] && TARGET="$cand"',
    "  done",
    "fi",
    '[ -z "$TARGET" ] && TARGET="$FALLBACK"',
    'exec node "$TARGET"',
    "",
  ].join("\n");
}

/** Single-quote a string for safe POSIX shell embedding. */
function shq(s: string): string {
  return `'${s.replace(/'/g, "'\\''")}'`;
}
